### ISSUE TITLE
Action element improperly replaces special characters

### ISSUE THREAD

**Issue by jswright61** [plivo/plivo-ruby#108]
If I supply a valid url including query string key value pairs which are properly separated by ampersands, those ampersands should not be replaced with HTML entities when the response is exported as xml.

```ruby
include Plivo::XML
r = Response.new
gd = r.GetDigits(action: "http://example.com/path?var1=a&var2=b&var3=c")
r.to_xml

# output: 
"<Response><GetDigits action='https://example.com/path?var1=a&amp;var2=b&amp;var3=c'/></Response>"

# expected (desired) output:
"<Response><GetDigits action='https://example.com/path?var1=a&var2=b&var3=c'/></Response>"
```
Please note that your current output seems inconsistent to me in that the question mark is not substituted but the ampersands are.

I would like to see the xml output simply select the string itself without substitution. If special characters exist in the url either before or after the query string, it should be on the developer utilizing the SDK to properly encode the strings.

If you are going to continue making the substitutions, perhaps consider altering the action element to allow a hash as an argument that would then get added to the url as the query string.

**Comment by huzaif-plivo** [comment]
@jswright61 Here, it's the expected behavior in XML. To represent "&" it needs to be escaped with "&amp;" and this doesn't alter your URL's when executed by Plivo. In the case of any queries, please feel free to contact the [support team](https://support.plivo.com/hc/en-us).
