### ISSUE TITLE
Could not validate the Signature caused by missed slash

### ISSUE THREAD

**Issue by acdesouza** [plivo/plivo-ruby#116]
I'm trying to validate the signature as explained at the documentation: [Generating and Validating the Signature
](https://www.plivo.com/docs/sms/getting-started/advanced/signature-validation/)

After a lot of trials and failures. I've downloaded the gem to understand what I'm missing.

Imagine my surprise when I get that the gem is the one who is missing something. A slash to be more specific :)

At the documentation, you should validate the response with:

`Base64.encode64(OpenSSL::HMAC.digest("SHA256", "AUTH_TOKEN", "YOUR_CALLBACK_URL/REQUEST_HEADER_X-Plivo-Signature-V2-Nonce"))
`

But, this never works. You never get a match the hash with the x-plivo-signature-v2, right? I've also tried to use the Auth Key, instead of Auth Token. And every combination of those fields.

To make it work you must change your code to this version:

`Base64.encode64(OpenSSL::HMAC.digest("SHA256", "AUTH_TOKEN", "YOUR_CALLBACK_URLREQUEST_HEADER_X-Plivo-Signature-V2-Nonce"))
`

Have you noticed the difference? Yep! Drop the slash between your callback URL and X-Plivo-Signature-V2-Nonce.

I verified it at the current implementation of [Plivo SDK(4.3.2)](https://github.com/plivo/plivo-ruby/blob/v4.3.2/lib/plivo/utils.rb#L106).

Of course, since it's working if you use the gem, the server must be generating the hash with this missing slash.

**Comment by acdesouza** [comment]
I also believe this is mainly caused by *my callback URL* doesn't end with a '/'

**Comment by nixonsam** [comment]
@acdesouza please check the updated [docs](https://www.plivo.com/docs/sms/guides/signature-validation) and let us know if you still face any issues. 

Thanks
