### ISSUE TITLE
implementation issues

### ISSUE THREAD

**Issue by Vishu0910** [plivo/plivo-ruby#177]
I am trying to implement send SMS api 

api = RestAPI.new("*","*")
api.send_message(params)
NoMethodError - undefined method `http_code' for #<KeyError: key not found: :ciphers>:

2nd version :
api = RestClient.new("*","*")
method 'new' is not defined for RestClient

**Comment by huzaif-plivo** [comment]
@Vishu0910 Version 1 is no longer supported. I would suggest you to follow the instruction to install Plivo Ruby SDK from [here](https://www.plivo.com/docs/sdk/server/ruby-sdk/)  and run the below to trigger SMS.

```ruby
require "plivo"
include Plivo

api = RestClient.new("<auth_id>","<auth_token>")
response = api.messages.create(
	src: "<sender_id>",
	dst:"<destination_number>",
	text:"Hello, this is a sample text",
	url: "https://foo.com/sms status/",
)
puts response
```

If you continue to have problems, please feel free to contact our [support-team](https://support.plivo.com/hc/en-us).
