### ISSUE TITLE
Faraday dependency is outdated

### ISSUE THREAD

**Issue by jamesst20** [plivo/plivo-ruby#179]
Hi,

Would it be possible to add support to v2.x aswell ?
I had dependencies conflict with Omniauth gems and that forced me to downgrade.

Thanks

**Comment by danillos** [comment]
Using Ruby 3.1.2 we keep having this warning.

```
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
```

I checked and it seems fixed in new Faraday versions.

**Comment by narayana-plivo** [comment]
@danillos @jamesst20 Please check v4.30.1

**Comment by narayana-plivo** [comment]
@danillos @jamesst20 closing PR. Updated faraday version.
@abhineet-plivo

**Comment by jamesst20** [comment]
@narayana-plivo 

Hi,

I am not sure what there is to check:

https://github.com/plivo/plivo-ruby/blob/5212898a17211b9631f41c7c2ecbb998618b024e/plivo.gemspec

```
  spec.add_dependency 'faraday', '~> 1.0'
```

Version is still lock to v1.0 thus blocking us from using v2.x.

Can you reopen the issue ?

**Comment by narayana-plivo** [comment]
@jamesst20 sure we will check and update you soon.
