### ISSUE TITLE
to_number and from_number are ignored in calls list api request

### ISSUE THREAD

**Issue by aliyazdani** [plivo/plivo-ruby#180]
Seems like the keys **from_number** and **to_number** are ignored in `calls.list` api calls.

`api.calls.list(to_number: 'some_valid_number')`
`api.calls.list(from_number: 'some_valid_number')`

Here is the list of keys in the method:
https://github.com/plivo/plivo-ruby/blob/master/lib/plivo/resources/calls.rb#L349

Here is a PR: https://github.com/plivo/plivo-ruby/pull/181

**Comment by abhishekGupta-Plivo** [comment]
We have released the changes suggested [v4.27.1](https://github.com/plivo/plivo-ruby/releases/tag/v4.27.1)
Thank you for the input
