### ISSUE TITLE
Faraday dependency is outdated. v1.x locked

### ISSUE THREAD

**Issue by james-em** [plivo/plivo-ruby#205]
Re-opening https://github.com/plivo/plivo-ruby/issues/179

> @narayana-plivo
> 
> Hi,
> 
> I am not sure what there is to check:
> 
> https://github.com/plivo/plivo-ruby/blob/5212898a17211b9631f41c7c2ecbb998618b024e/plivo.gemspec
> 
> ```
>   spec.add_dependency 'faraday', '~> 1.0'
> ```
> 
> Version is still lock to v1.0 thus blocking us from using v2.x.
> 
> Here is `bundle outdated` from my project
> 
> ```
> Gem                          Current  Latest   Requested  Groups
> faraday                      1.10.3   2.7.4
> faraday-excon                1.1.0    2.1.0
> faraday-httpclient           1.0.1    2.0.1
> faraday-net_http             1.0.1    3.0.2
> faraday-net_http_persistent  1.2.0    2.1.0
> faraday-patron               1.0.0    2.0.1
> faraday-rack                 1.0.0    2.0.0
> faraday-retry                1.0.3    2.0.0
> rack                         2.2.6.2  3.0.4.1
> ```
> 
> Can you reopen the issue ?

**Comment by rgalanakis** [comment]
This also leads to this warning:
```
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
```

**Comment by narayana-plivo** [comment]
@james-em please check on latest version : https://github.com/plivo/plivo-ruby/releases/tag/v4.49.0

cc @mallika-plivo

**Comment by narayana-plivo** [comment]
closing the issue. On latest build we have upgraded the  farady version
