### ISSUE TITLE
Add a Timeout

### ISSUE THREAD

**Issue by naysawn** [plivo/plivo-ruby#22]
I'm finding that sometimes the Plivo API isn't responsive. In this case, it can cause the app to hang waiting for a response.  

I think the simple fix would be to add a timeout parameter to the RestClient::Resource.new instantiation. 

http://rubydoc.info/gems/rest-client/1.6.1/RestClient/Resource#timeout-instance_method

**Comment by tsudot** [comment]
Could you please send a pull request? The last PR could not be merged because master has diverged.
