### ISSUE TITLE
Impossible to validate XPlivoSignature in a Rails controller

### ISSUE THREAD

**Issue by moserrya** [plivo/plivo-ruby#25]
This seems pretty straightforward so I am not sure what is causing the problem. I am trying to authorize messages coming from Plivo in a Rails controller but the following is not working:

``` ruby
signature    = request.headers["HTTP_X_PLIVO_SIGNATURE"]
auth_token = PLIVO_CONFIG[:auth_token] # let's assume this is set up correctly; works for outbound messages
uri = request.original_url
post_params = request.request_parameters

XPlivoSignature.new(signature, uri, post_params, auth_token).is_valid? # => false
```

Is there some gotcha to making this work as expected?

**Comment by mntdamania** [comment]
+1 @moserrya. @tsudot can you please guide here?

**Comment by tsudot** [comment]
@mntdamania @guillec Could you give me the specific Plivo API which does not contain the X_PLIVO_SIGNATURE header? I can look into this.

**Comment by mntdamania** [comment]
@tsudot I'm getting X_PLIVO_SIGNATURE header back when I use incoming SMS webhook, but not able to verify the authenticity of the header with above mentioned code.

**Comment by tsudot** [comment]
Incoming SMS currently does not send a X_PLIVO_SIGNATURE header. I'm keeping this open until we fix this in the backend.

**Comment by lpopa** [comment]
Any updates related to XPlivoSignature#is_valid? I am getting X_PLIVO_SIGNATURE in the header, but no matter how I try to format the params and the uri I can't get it to validate.

**Comment by Ramya-Raghu** [comment]
Examples on how to validate - https://github.com/plivo/plivo-examples-ruby/blob/master/sms/validate_signatue.rb
https://github.com/plivo/plivo-examples-ruby/blob/master/voice/validate_signature.rb

**Comment by mntdamania** [comment]
If If vw wyou

**Comment by mntdamania** [comment]
wcw mbcwb

**Comment by mntdamania** [comment]
If not vzcx

**Comment by lpopa** [comment]
@Ramya-Raghu i did follow the examples you suggested and I can't seem to validate the signature locally. I am using ngrok to post to my localhost. Here is  what i get:
```
"SIGNATURE IN HEADER: 62Gv0PVoiUHkSovfiYBN0QnRZw4="
"URI: https://81c9a82b.ngrok.io/sms"
"PARAMS: {\"To\"=>\"14156121624\", \"From\"=>\"13107034177\", \"TotalRate\"=>\"0\", \"Units\"=>\"1\", \"Text\"=>\"test\", \"TotalAmount\"=>\"0\", \"Type\"=>\"sms\", \"MessageUUID\"=>\"eb9bbc60-8eef-11e5-a4b5-22000afd08f6\"}"
"AUTH_TOKEN: NjYzMzkxZDI1OTE5M2Y4YTU5YjY4MjBiNDMyODBl"
"URI in#is_valid?: https://81c9a82b.ngrok.io/smsFrom13107034177MessageUUIDeb9bbc60-8eef-11e5-a4b5-22000afd08f6TexttestTo14156121624TotalAmount0TotalRate0TypesmsUnits1"
Base64.encode64(OpenSSL::HMAC.digest('sha1', 'NjYzMzkxZDI1OTE5M2Y4YTU5YjY4MjBiNDMyODBl', 'https://81c9a82b.ngrok.io/smsFrom13107034177MessageUUIDeb9bbc60-8eef-11e5-a4b5-22000afd08f6TexttestTo14156121624TotalAmount0TotalRate0TypesmsUnits1')).chomp == 'R5eXLihOQfgBs99VrEERrsthvTw='

false
```
Any help would be greatly appreciated .

PS: Current environment i am working with:
ruby 2.1.7p400
Rails 3.2.22
rest-client (1.8.0)
json (1.8.3, 1.8.2, 1.8.1)
htmlentities (4.3.4)

**Comment by cachrisman** [comment]
can you share the code you are using to check the signature? I took the parameters, etc. you shared and calculated the signature and got the same result as you. But when I used the verify signature example code Ramya shared and set up a plivo number and application to point to my ngrok url, I was able to successfully verify the signature.

Here is the code I used if that helps:
```ruby
require 'sinatra'
require 'rubygems'
require 'plivo'
include Plivo
require 'uri'

post '/message/' do
    signature = request.env["HTTP_X_PLIVO_SIGNATURE"]
    uri = request.url
    params = Hash.new{[]}
    auth_token = "YWE2MzczYmYxNDBhNDhiMDBjMzY1YTZhNGI1Yjhi" # put your auth_token from the account assigned to the Plivo number and to the Plivo application here

    post_params = request.body.read
    if post_params
        params = params.merge(Hash[*URI.decode_www_form(post_params).flatten])
    end

    p "Signature: #{signature}"
    p "URI: #{uri}"
    puts "Params: #{params}"
    p "Auth Token: #{auth_token}"

    message_signature = XPlivoSignature.new(signature,uri,params,auth_token)
    puts "Valid Signature: #{message_signature.is_valid?()}"

    from_number = params["From"]
    to_number = params["To"]
    text = params["Text"]
    puts "Message received from #{from_number} : #{text}"
end
```

have you set up your Plivo number and Plivo application correctly?

**Comment by lpopa** [comment]
```
class User::PlivoSmsController < ApplicationController
  before_filter :verify_plivo_signature
private 

def verify_plivo_signature
    auth_token = ENV['PLIVO_AUTH_TOKEN']
    signature = request.env["HTTP_X_PLIVO_SIGNATURE"]
    url = request.url
    uri = (url.split("?"))[0]

    post_params = request.body.read
    formated_params = Hash.new{[]}
    formated_params = formated_params.merge(Hash[*URI.decode_www_form(post_params).flatten]) if post_params

    valid = Plivo::XPlivoSignature.new(signature,uri,formated_params,auth_token)

    pp "SIGNATURE IN HEADER: #{signature}"
    pp "URI: #{uri}"
    pp "PARAMS: #{formated_params}"
    pp "AUTH_TOKEN: #{auth_token}"
    puts valid.is_valid?
  end
end
```
#sms POST   /sms(.:format)                                                        user/plivo_sms#create

Plivo Application
Message URL: https://81c9a82b.ngrok.io/sms
Message Method: POST
Number i am texting back has the correct application associated.

Plivo Account: 
SubAccount for staging with the auth_token provided.

**Comment by husam212** [comment]
I had the same issue, keeping the query string (using `url` instead if `uri`) worked for me.
