### ISSUE TITLE
Security update for POODLE vulnerability

### ISSUE THREAD

**Issue by apecherin** [plivo/plivo-ruby#30]
Hello, yesterday I got next email from Plivo support-
"Hi,
We wanted to let you know that we will be disabling support for SSL 3.0 on December 30th in light of the latest security vulnerability discovered by Google. This vulnerability, nicknamed POODLE (Padding Oracle On Downgraded Legacy Encryption), allows attackers to decrypt encrypted website connections and steal sensitive information.
Fortunately, TLS (transport layer security) has been the industry standard for the last 15 years and SSL 3.0 is hardly used. Though to ease this transition, we will give our customers time to make changes to their app so that all of your HTTPS requests use TLS. You most likely will not be affected, but please double check that:
HTTPS Client code supports making API requests with TLS - as Plivo servers will reject SSLv3 connection attempts.
Customer web servers serving Plivo Application URLs (e.g. answer_url) over HTTPS will have to support TLS - requests from Plivo will not be made over SSLv3.
WebRTC clients will have to support TLS - this is usually the case when the WebRTC client is a recent browser and using Plivo’s WebSDK.
Please make these updates asap as we will disable support for SSL 3.0. on Tuesday December 30th, 2014, at 9am PST. "

So, now I see that can't set specific ssl_version for Plivo::RestAPI.new()
what your mind about it?

I spent a quick analysis -
I saw that now my "rest-client" gem have old version and using SSLv3 as default(and in this version I can't change :ssl_version even).
but and in a new version using SSLv23 (https://github.com/treeder/rest_client/commit/ae72fa75555ae8a20b51402461fb3adeb6bb3f50).
even if I'll switch to this version, we can't set :ssl_version as TSL, because call rest-request is hardcoded in "plivo-gem".

Could you please release patch for this?

**Comment by tsudot** [comment]
The current gem works without any issues related to SSL.
