### ISSUE TITLE
Implicit Rake dependency?

### ISSUE THREAD

**Issue by daaain** [plivo/plivo-ruby#41]
The gem failed to install until I put its Rake dependency into my own Gemfile, see Bundler error message below:

```
Installing plivo 0.3.19 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/plivo-0.3.19/ext
/usr/local/bin/ruby mkrf_conf.rb

current directory: /usr/local/bundle/gems/plivo-0.3.19/ext
rake RUBYARCHDIR=/usr/local/bundle/extensions/x86_64-linux/2.3.0-static/plivo-0.3.19 RUBYLIBDIR=/usr/local/bundle/extensions/x86_64-linux/2.3.0-static/plivo-0.3.19
/usr/local/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'rake' (>= 0.a) among 24 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/usr/local/bundle', execute `gem env` for more information
    from /usr/local/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
    from /usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
    from /usr/local/bin/rake:22:in `<main>'

rake failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/plivo-0.3.19 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.3.0-static/plivo-0.3.19/gem_make.out
An error occurred while installing plivo (0.3.19), and Bundler cannot continue.
Make sure that `gem install plivo -v '0.3.19'` succeeds before bundling.
The command '/bin/sh -c bundle install' returned a non-zero code: 5
```

**Comment by dscher** [comment]
I had the same issue, although only while deploying to Heroku. Adding 'rake' to my Gemfile explicitly fixed the issue.

`remote:        Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
remote:        
remote:        current directory: /tmp/build_527c452e61f1b5fe07911055c6c3ad79/vendor/bundle/ruby/2.3.0/gems/plivo-0.3.19/ext
remote:        /tmp/build_527c452e61f1b5fe07911055c6c3ad79/vendor/ruby-2.3.0/bin/ruby mkrf_conf.rb
remote:        
remote:        current directory: /tmp/build_527c452e61f1b5fe07911055c6c3ad79/vendor/bundle/ruby/2.3.0/gems/plivo-0.3.19/ext
remote:        rake RUBYARCHDIR=/tmp/build_527c452e61f1b5fe07911055c6c3ad79/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0-static/plivo-0.3.19 RUBYLIBDIR=/tmp/build_527c452e61f1b5fe07911055c6c3ad79/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0-static/plivo-0.3.19
remote:        /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'rake' (>= 0.a) among 28 total gem(s) (Gem::LoadError)
remote:        Checked in 'GEM_PATH=/tmp/build_527c452e61f1b5fe07911055c6c3ad79/vendor/bundle/ruby/2.3.0', execute `gem env` for more information
remote:        from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
remote:        from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
remote:        from /app/bin/rake:22:in `<main>'
remote:        
remote:        rake failed, exit code 1
remote:        
remote:        Gem files will remain installed in /tmp/build_527c452e61f1b5fe07911055c6c3ad79/vendor/bundle/ruby/2.3.0/gems/plivo-0.3.19 for inspection.
remote:        Results logged to /tmp/build_527c452e61f1b5fe07911055c6c3ad79/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0-static/plivo-0.3.19/gem_make.out
remote:        An error occurred while installing plivo (0.3.19), and Bundler cannot continue.
remote:        Make sure that `gem install plivo -v '0.3.19'` succeeds before bundling.
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
remote: 
`

**Comment by daaain** [comment]
@dscher well I guess you have Rake installed globally on your machine, just like the library author.

I'm using Docker for development, so it's a clean environment where you can't assume stuff already being there, just like Heroku.

**Comment by dscher** [comment]
Just trying to understand....

So Heroku would only install the top level dependencies of the plivo gem? 

Gem plivo-0.3.19
  builder (>= 2.1.2)
  htmlentities (>= 4.3.1, ~> 4.3)
  json (>= 1.6.6, ~> 1.6)
  rest-client (>= 1.6.7, ~> 1.6)

I ran `gem list` in a Heroku shell and got this list:

activemodel (4.2.6)
activerecord (4.2.6)
activesupport (4.2.6)
arel (6.0.3)
bigdecimal (1.2.8)
builder (3.2.2)
bundler (1.9.7)
did_you_mean (1.0.0)
domain_name (0.5.20160216)
htmlentities (4.3.4)
http-cookie (1.0.2)
i18n (0.7.0)
io-console (0.4.5)
json (1.8.3)
mime-types (2.99.1)
minitest (5.8.4, 5.8.3)
net-telnet (0.1.1)
netrc (0.11.0)
pg (0.18.4)
plivo (0.3.19)
power_assert (0.2.6)
psych (2.0.17)
rack (1.6.4)
rack-protection (1.5.3)
rake (10.5.0, 10.4.2)
rdoc (4.2.1)
rest-client (1.8.0)
sinatra (1.4.7)
test-unit (3.1.5)
thread_safe (0.3.5)
tilt (2.0.2)
tzinfo (1.2.2)
unf (0.1.4)
unf_ext (0.0.7.2)
~ $ 

but when I look at the dependencies of the gems in my Gemfile individually, it doesn't account for all of the above gems. 

```
gem 'sinatra'
gem 'activerecord'
gem 'rake'
gem 'plivo', '~> 0.3.19'
gem 'pg'

```

**Comment by daaain** [comment]
I'm not sure how Heroku installs Gems (probably Bundler), but it should definitely install the whole dependency tree.

The whole problem might be due to this external build file which I don't really understand: https://github.com/plivo/plivo-ruby/blob/master/ext/mkrf_conf.rb

**Comment by dscher** [comment]
I don't understand it either.

openssl is required in plivo.rb anyway and there don't seem to be any calls
to that mkrf_conf.rb file.

Perhaps someone else will chime in at some point.

Thanks.


David

**Comment by daaain** [comment]
There is a call in the `.gemspec`, which would also explain why the error is during build time: https://github.com/plivo/plivo-ruby/blob/master/plivo.gemspec#L18

**Comment by dscher** [comment]
Ahhhh...missed that. 

Whoever added that code got it from: https://en.wikibooks.org/wiki/Ruby_Programming/RubyGems

**Comment by cachrisman** [comment]
I'm one of the maintainers of this project; if you want to submit a PR I'll look it over soon

**Comment by daaain** [comment]
I looked into it a bit more, and it seems those lines are in fact needed for the hack to work (see http://www.programmersparadox.com/2012/05/21/gemspec-loading-dependent-gems-based-on-the-users-system/). So as I understand the reason for this fake external build process is to check if OpenSSL is installed. Would it not be better then to just require it as runtime dependency?

Or if there's a good reason why that can't work, then Rake should be added as a dependency since it is required during the local build process.

Since I don't know the reason behind using this whole external dependency workaround, if I was to put a PR in I'd just go down the second path and add Rake to make sure I'm not breaking anything.

**Comment by dscher** [comment]
@daaain It makes sense for Rake to be added as a dependency if there isn't another workaround here that is less confounding.

**Comment by daaain** [comment]
OK, finally got around to put the PR (#42) in with a couple other small fixes I spotted on the way :)
