### ISSUE TITLE
wrong attribute name on Record object

### ISSUE THREAD

**Issue by ephekt** [plivo/plivo-ruby#45]
In the Record attribute on a Call object in the REST API the proper key parameter for maximum length of a call recording is `time_limit` but in the code it is `maxLength` -- this should be `timeLimit`. Hope this helps someone else.

https://github.com/plivo/plivo-ruby/blob/master/lib/plivo.rb#L769

**Comment by Ramya-Raghu** [comment]
@ephekt : The parameter maxLength used [here](https://github.com/plivo/plivo-ruby/blob/master/lib/plivo.rb#L769) is for the [Record XML](https://www.plivo.com/docs/xml/record/). The function [here](https://github.com/plivo/plivo-ruby/blob/master/lib/plivo.rb#L263) is used to a start recording on a Call using the API, for which time_limit would be the right parameter as given in the [docs](https://www.plivo.com/docs/api/call/record/).

**Comment by ephekt** [comment]
Thanks. The documentation was tough to figure out. I'm finding the xml docs
are pretty solid.

On Tue, Jun 28, 2016 at 10:58 PM, Ramya-Raghu <notifications@github.com>
wrote:

> Closed #45 <https://github.com/plivo/plivo-ruby/issues/45>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/plivo/plivo-ruby/issues/45#event-707299833>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AACLd4S5hoF5IuwCapGIiKmKgNP_ILb2ks5qQglzgaJpZM4JArB5>
> .
>



-- 

LinkedIn <http://www.linkedin.com/in/michaelrosengarten> | @smasher5
<http://www.twitter.com/smasher5> | mfrosengarten@gmail.com
