### ISSUE TITLE
Depends on rest-client 2.0

### ISSUE THREAD

**Issue by duane** [plivo/plivo-ruby#53]
Is there any chance you could either:

1) Drop the dependency on rest-client 1.x.
2) Update rest-client to 2.0.
3) Use the standard library http client
4) Use a recent stable version of faraday.

The use of the gem dependency on rest-client 1.x means, e.g., you cannot use this gem in the same process that you use any version of mailgun since 2015 began—2.5 years of not updating rest-client is way too long.

**Comment by pelegb** [comment]
+1
And update json dependency as well.

**Comment by plivo-sdks** [comment]
Check out the 4.0 branch for the new SDK which fixes this.
