### ISSUE TITLE
Fix tests to avoid rspec concealing required dependencies

### ISSUE THREAD

**Issue by Sreyanth** [plivo/plivo-ruby#57]
This is the reason why #55 wasn't caught. Need to fix all tests where this might be happening to "really test" the SDK.

**Comment by Sreyanth** [comment]
More details: https://stackoverflow.com/questions/13667900/how-do-i-prevent-rspec-from-concealing-missing-dependencies

**Comment by plivo-sdks** [comment]
Closing this for now as there doesn't seem to be a clean way of fixing this. All issues that aren't being detected due to this will be fixed on a case-by-case basis.
