### ISSUE TITLE
Deprecation warnings reminder

### ISSUE THREAD

**Issue by viktorsmari** [plivo/plivo-ruby#60]
.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/plivo-4.1.0/lib/plivo/utils.rb:70: warning: constant ::Fixnum is deprecated

.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/plivo-4.1.0/lib/plivo/utils.rb:70: warning: constant ::Bignum is deprecated

**Comment by KiranPanesar** [comment]
👍 to this. Any ETA?

**Comment by BenMorganIO** [comment]
Wondering the same thing. Would love to see these fixed.

**Comment by kapso** [comment]
Any ETA around this issue?

**Comment by BenMorganIO** [comment]
I'd recommend using the fork.

**Comment by nixonsam** [comment]
This will be done in a week's time.

**Comment by nixonsam** [comment]
This was fixed and released, https://github.com/plivo/plivo-ruby/releases/tag/v4.1.6.

closing this issue.
