### ISSUE TITLE
Request: Add callback URL to the Send Message Example

### ISSUE THREAD

**Issue by viktorsmari** [plivo/plivo-ruby#61]
It would be really helpful if the Send Message Example in README.md would include info on how to supply the Callback URL.

The [original documentation](https://api-reference.plivo.com/latest/ruby/resources/message/send-a-message) also does not show example how to do it. Here is their example:
```
response = api.messages.create(
    '14153336666',
    ['14156667777', 123_123_123_123],
    'Test Message'
  )
```

How would one supply the Callback url? Would it be something like this?
```
response = api.messages.create(
    '14153336666',
    ['14156667777', 123_123_123_123],
    'Test Message',
    { 'url' => 'http://example.com/api/confirmsms/' }

  )
```

**Comment by KiranPanesar** [comment]
Had this same issue, talked with Plivo's support team and they had this solution:

```
        $plivo_client.messages.create(
          'from_number',
          [to_numbebr],
          'message',
          url: "http://example.com/api/confirmsms"
        )
```

@joe-plivo I'd suggest adding this example to the API Docs 😃

**Comment by joe-plivo** [comment]
Will do.

**Comment by nixonsam** [comment]
API [Docs](https://www.plivo.com/docs/sms/detailed-reference/api/message/send-a-message/) is updated with this.

Thank you!
