### ISSUE TITLE
silent failures when phone number format isn't exactly as expected

### ISSUE THREAD

**Issue by ghost** [plivo/plivo-ruby#78]
if the country code isn't specified or if the phone number contains dashes or periods, the call silently fails (this was with `client.messages.create` https://github.com/plivo/plivo-ruby/#send-a-message)

I have this simple code to format as expected, but it'd be great if the API provided this flexibility by default (especially given the fact that no errors are reported)
```ruby
def format_number(number)
  # strip out any non-numeric characters
  num = number.gsub(/[^0-9]/, '')
  # prepend country code
  num.prepend(COUNTRY_CODE) if num.length < PHONE_DIGITS
  num
end
```
Thanks!

**Comment by DeblinaC** [comment]
@ghost Phone number validation is being handled in the latest version (https://github.com/plivo/plivo-ruby/releases/tag/v4.3.0).
