### ISSUE TITLE
undefined local variable or method number_list (in Resources/Numbers.rb)

### ISSUE THREAD

**Issue by binarygeek** [plivo/plivo-ruby#87]
While running this code:
```
client = Plivo::RestClient.new(@auth_id, @auth_token)
client.phone_numbers.each('US') do |obj|
  puts obj.number
end
```
I get the following error:

`undefined local variable or method number_list`

which can be tracked down to the line below (seems the variable should be called phone_number_list instead):

https://github.com/plivo/plivo-ruby/blob/d588e2af8041a5ad67ea209418bea264816b8873/lib/plivo/resources/numbers.rb#L113

**Comment by nixonsam** [comment]
@binarygeek This issue has been fixed in the new [release](https://github.com/plivo/plivo-ruby/releases/tag/v4.3.0)
